theme: jekyll-theme-minimal
title: Simon Martina-Perez
logo: Images/SMP_profile.jpeg
description: Get in touch! Email me at martinaperez [at] maths [dot] ox [dot] ac [dot] uk, on Twitter as @simonmape
